name: Run Go Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod tidy

      - name: Run application
        run: go run main.go
        env:
          CLICKHOUSE_DSN: ${{ secrets.CLICKHOUSE_DSN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
